[workspace]
members = [
    "crates/hdim-core",
    "crates/hdim-render",
    "crates/hdim-tui",
]
resolver = "2"

[package]
name = "hdim"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The official CLI for the High Definition Image Manipulator."
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
hdim-tui = { workspace = true }
anyhow = { workspace = true }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Matteo Bosshard <matteobosshard@gmail.com>"]
description = "High Definition Image Manipulator (HDIM) - A terminal-based image editor."
repository = "https://github.com/HardBoss07/hdim"
license = "GPL-3.0"
# Refined slugs based on crates.io categories
keywords = ["image", "tui", "editor", "terminal", "graphics"]
categories = ["command-line-utilities", "multimedia::graphics", "multimedia::images"]
readme = "README.md"

[workspace.dependencies]
# Internal Workspace Crates
hdim-core = { path = "crates/hdim-core", version = "0.1.0" }
hdim-render = { path = "crates/hdim-render", version = "0.1.0" }
hdim-tui = { path = "crates/hdim-tui", version = "0.1.0" }

# Graphics & Math
image = "0.25"
crossterm = "0.29"
ratatui = "0.30"
palette = "0.7.6"
ansi-to-tui = "8.0.1"
rand = "0.8.5"

# Exif Data Management
kamadak-exif = "0.6.1"
img-parts = "0.3"

# Error Handling & Utils
anyhow = "1.0"
thiserror = "1.0"
color-eyre = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "6.0"

# Testing
insta = "1.34"