[package]
name = "hdim-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core logic and image manipulation algorithms for HDIM."
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[features]
default = []
exif = ["dep:kamadak-exif", "dep:img-parts"]

[dependencies]
image = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
kamadak-exif = { workspace = true, optional = true }
img-parts = { workspace = true, optional = true }
palette = { workspace = true, features = ["serde"] }
rand = { workspace = true }
serde = { workspace = true }