use super::*;

pub fn get_localization() -> Localization {
    Localization {
        tools: Tools {
            title: " WERKZEUGE ".to_string(),
            crop: "Zuschneiden".to_string(),
            metadata: "Metadaten".to_string(),
            export: "Exportieren".to_string(),
            adjust: "Anpassen".to_string(),
            placeholder: "Wählen Sie ein Werkzeug aus".to_string(),
        },
        status: Status {
            normal: " NORMAL ".to_string(),
            edit_value: " WERT BEARBEITEN ".to_string(),
            crop: " ZUSCHNEIDEN ".to_string(),
            metadata: " METADATEN ".to_string(),
            exporting: " EXPORTIEREN ".to_string(),
            confirm_quit: " BEENDEN BESTÄTIGEN ".to_string(),
            hint_adjust: "↑/↓ Wählen • ←/→ Anpassen • Enter Manuell • Esc Zurück".to_string(),
            hint_normal: "Pfeiltasten Bewegen • PgUp/Dn Zoom • 1-4 Werkzeuge • Ctrl+q Beenden"
                .to_string(),
        },
        common: Common {
            unknown: "Unbekannt".to_string(),
            error_rendering: "Fehler beim Rendern des Bildes".to_string(),
        },
        adjustments: Adjustments {
            title: " Anpassungen ".to_string(),
            brightness: "Helligkeit".to_string(),
            contrast: "Kontrast".to_string(),
            exposure: "Belichtung".to_string(),
            fade: "Verblassen".to_string(),
            grain: "Korn".to_string(),
            hue: "Farbton".to_string(),
            noise: "Rauschen".to_string(),
            saturation: "Sättigung".to_string(),
            vibrance: "Dynamik".to_string(),
            warmth: "Wärme".to_string(),
        },
        exif: Exif {
            title: " EXIF Daten ".to_string(),
            general: "Allgemein:".to_string(),
            date_time: "  Zeitpunkt: ".to_string(),
            camera: "Kamera:".to_string(),
            make: "  Hersteller: ".to_string(),
            model: "  Modell: ".to_string(),
            software: "  Software: ".to_string(),
            exposure: "Belichtung:".to_string(),
            exposure_time: "  Belichtungszeit: ".to_string(),
            f_number: "  Blende: ".to_string(),
            iso: "  ISO: ".to_string(),
            lens: "Objektiv:".to_string(),
            focal_length: "  Brennweite: ".to_string(),
            f_number_range: "  Blendenbereich: ".to_string(),
            image: "Bild:".to_string(),
            width: "  Breite: ".to_string(),
            height: "  Höhe: ".to_string(),
            gps: "GPS:".to_string(),
            latitude: "  Breitengrad: ".to_string(),
            longitude: "  Längengrad: ".to_string(),
            altitude: "  Höhe: ".to_string(),
        },
        crop: Crop {
            title: "Zuschneideoptionen".to_string(),
            left: "Links".to_string(),
            right: "Rechts".to_string(),
            top: "Oben".to_string(),
            bottom: "Unten".to_string(),
            from_viewport: "Aus Ansicht zuschneiden".to_string(),
        },
        export: Export {
            title: " BILD EXPORTIEREN ".to_string(),
            select_format: "Format wählen:".to_string(),
            filename: "Dateiname: ".to_string(),
        },
        confirm_quit: ConfirmQuit {
            title: " UNGESPEICHERTE ÄNDERUNGEN ".to_string(),
            message: "Sie haben ungespeicherte Änderungen.".to_string(),
            question: "Sind Sie sicher, dass Sie beenden möchten?".to_string(),
            yes: "[Y] Ja (Beenden)".to_string(),
            no: "[N] Nein (Abbrechen)".to_string(),
        },
        settings: Settings {
            title: " EINSTELLUNGEN ".to_string(),
            language: "Sprache: ".to_string(),
            theme: "Farbschema: ".to_string(),
            strip_exif: "Sensible EXIF entfernen: ".to_string(),
            save: "[S] Speichern".to_string(),
            cancel: "[Esc] Abbrechen".to_string(),
        },
    }
}
