use super::*;

pub fn get_localization() -> Localization {
    Localization {
        tools: Tools {
            title: " Tools ".to_string(),
            transform: "Transform".to_string(),
            metadata: "Metadata".to_string(),
            export: "Export".to_string(),
            adjust: "Adjust".to_string(),
            placeholder: "Select a tool to begin editing".to_string(),
        },
        status: Status {
            normal: " NORMAL ".to_string(),
            edit_value: " EDIT VALUE ".to_string(),
            transform: " TRANSFORM ".to_string(),
            metadata: " METADATA ".to_string(),
            exporting: " EXPORTING ".to_string(),
            confirm_quit: " CONFIRM QUIT ".to_string(),
            hint_adjust: "↑/↓ Select • ←/→ Adjust • Enter Manual • Esc Back".to_string(),
            hint_transform: "↑/↓ Select • Enter Toggle/Edit • Esc Back".to_string(),
            hint_normal: "Arrows Pan • PgUp/Dn Zoom • 1-4 Tools • Ctrl+q Quit".to_string(),
        },
        common: Common {
            unknown: "Unknown".to_string(),
            error_rendering: "Error rendering image".to_string(),
        },
        adjustments: Adjustments {
            title: " Adjustments ".to_string(),
            brightness: "Brightness".to_string(),
            contrast: "Contrast".to_string(),
            exposure: "Exposure".to_string(),
            fade: "Fade".to_string(),
            grain: "Grain".to_string(),
            hue: "Hue".to_string(),
            noise: "Noise".to_string(),
            saturation: "Saturation".to_string(),
            vibrance: "Vibrance".to_string(),
            warmth: "Warmth".to_string(),
        },
        exif: Exif {
            title: " Exif Data ".to_string(),
            no_data: " No Metadata found ".to_string(),
            general: "General:".to_string(),
            date_time: "  Date Time: ".to_string(),
            camera: "Camera:".to_string(),
            make: "  Make: ".to_string(),
            model: "  Model: ".to_string(),
            software: "  Software: ".to_string(),
            exposure: "Exposure:".to_string(),
            exposure_time: "  Exposure Time: ".to_string(),
            f_number: "  F Number: ".to_string(),
            iso: "  ISO: ".to_string(),
            lens: "Lens:".to_string(),
            focal_length: "  Focal Length: ".to_string(),
            f_number_range: "  F Number Range: ".to_string(),
            image: "Image:".to_string(),
            width: "  Width: ".to_string(),
            height: "  Height: ".to_string(),
            gps: "GPS:".to_string(),
            latitude: "  Latitude: ".to_string(),
            longitude: "  Longitude: ".to_string(),
            altitude: "  Altitude: ".to_string(),
        },
        transform: Transform {
            title: " Transform Options ".to_string(),
            left: "Left".to_string(),
            right: "Right".to_string(),
            top: "Top".to_string(),
            bottom: "Bottom".to_string(),
            rotate_left: "Rotate Left".to_string(),
            rotate_right: "Rotate Right".to_string(),
            flip_horizontal: "Flip Horizontal".to_string(),
            flip_vertical: "Flip Vertical".to_string(),
            from_viewport: "Crop from viewport".to_string(),
            apply: "Apply Transform".to_string(),
            confirm_cancel: " Unapplied Changes ".to_string(),
            confirm_cancel_msg: "You have unapplied transform changes. Discard?".to_string(),
        },
        export: Export {
            title: " Export Image ".to_string(),
            select_format: "Select format:".to_string(),
            filename: "Filename: ".to_string(),
        },
        confirm_quit: ConfirmQuit {
            title: " Unsaved Changes ".to_string(),
            message: "You have unsaved changes.".to_string(),
            question: "Are you sure you want to quit?".to_string(),
            yes: "[Y] Yes (Quit)".to_string(),
            no: "[N] No (Cancel)".to_string(),
        },
        settings: Settings {
            title: " Settings ".to_string(),
            language: "Language: ".to_string(),
            theme: "Theme: ".to_string(),
            strip_exif: "Strip sensitive EXIF: ".to_string(),
            save: "[S] Save".to_string(),
            cancel: "[Esc] Cancel".to_string(),
        },
    }
}
